// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4ouu9utc9-W32wRiIh-3bL8IBRUI1Q4U',
    appId: '1:979979882370:web:0603d61892b89c64bf899b',
    messagingSenderId: '979979882370',
    projectId: 'tpiprogrammingclub',
    authDomain: 'tpiprogrammingclub.firebaseapp.com',
    databaseURL: 'https://tpiprogrammingclub-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tpiprogrammingclub.appspot.com',
    measurementId: 'G-SX5J7BV9P0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr5KcJK_k89HC-FbV-RxByBX1z1uIsolA',
    appId: '1:979979882370:android:94106b6343888e23bf899b',
    messagingSenderId: '979979882370',
    projectId: 'tpiprogrammingclub',
    databaseURL: 'https://tpiprogrammingclub-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tpiprogrammingclub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXICGCiS9PMQv8wAY9PvEIwDZD6FlU268',
    appId: '1:979979882370:ios:39a278f25b5e1ae6bf899b',
    messagingSenderId: '979979882370',
    projectId: 'tpiprogrammingclub',
    databaseURL: 'https://tpiprogrammingclub-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tpiprogrammingclub.appspot.com',
    androidClientId: '979979882370-5j41lglqi81m9oilg0kqdh4aea8gjflp.apps.googleusercontent.com',
    iosClientId: '979979882370-000vaavi6eem8gmt4qvt0ss7e8kdfeke.apps.googleusercontent.com',
    iosBundleId: 'com.example.tpiProgrammingClub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXICGCiS9PMQv8wAY9PvEIwDZD6FlU268',
    appId: '1:979979882370:ios:39a278f25b5e1ae6bf899b',
    messagingSenderId: '979979882370',
    projectId: 'tpiprogrammingclub',
    databaseURL: 'https://tpiprogrammingclub-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tpiprogrammingclub.appspot.com',
    androidClientId: '979979882370-5j41lglqi81m9oilg0kqdh4aea8gjflp.apps.googleusercontent.com',
    iosClientId: '979979882370-000vaavi6eem8gmt4qvt0ss7e8kdfeke.apps.googleusercontent.com',
    iosBundleId: 'com.example.tpiProgrammingClub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4ouu9utc9-W32wRiIh-3bL8IBRUI1Q4U',
    appId: '1:979979882370:web:514b453a583896a9bf899b',
    messagingSenderId: '979979882370',
    projectId: 'tpiprogrammingclub',
    authDomain: 'tpiprogrammingclub.firebaseapp.com',
    databaseURL: 'https://tpiprogrammingclub-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tpiprogrammingclub.appspot.com',
    measurementId: 'G-RRRJQVW197',
  );
}
