// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Iat7HTtnKDAivp8uZ1xLKyuY0BXzMf8',
    appId: '1:95856586450:web:67ef917ed04f3352d7070b',
    messagingSenderId: '95856586450',
    projectId: 'developersunited',
    authDomain: 'developersunited.firebaseapp.com',
    databaseURL: 'https://developersunited-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'developersunited.appspot.com',
    measurementId: 'G-Y0YL660RW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVtqYHOY5haACKNuRN0I2wc7VgDEhesTU',
    appId: '1:95856586450:android:97eea9e49f39f614d7070b',
    messagingSenderId: '95856586450',
    projectId: 'developersunited',
    databaseURL: 'https://developersunited-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'developersunited.appspot.com',
  );
}
